name: CI - Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports: ['27017:27017']

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Configuration Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installation des dépendances
      run: |
        pip install -r back/requirements.txt

    - name: Vérification que Mongo est prêt
      run: |
        for i in {1..10}; do
          nc -z mongo 27017 && echo "Mongo est prêt" && exit 0
          echo "En attente de Mongo..."
          sleep 5
        done
        echo "Mongo n'a pas démarré à temps" && exit 1

    - name: Test de connexion MongoDB en Python
      run: |
        python -c "from pymongo import MongoClient; client = MongoClient('mongodb://mongo:27017'); print(client.server_info())"
