name: CI - Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports: ['27017:27017']

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: |
          pip install -r back/requirements.txt

      - name: Vérifier que MongoDB est prêt avec pymongo
        run: |
          pip install pymongo
          python -c "
import time
from pymongo import MongoClient
for i in range(10):
    try:
        client = MongoClient('mongodb://mongo:27017', serverSelectionTimeoutMS=1000)
        print(client.server_info()) 
        print('Mongo est prêt')
        break
    except Exception as e:
        print(f'Tentative {i+1}: Mongo pas encore prêt -', e)
        time.sleep(3)
else:
    print('Mongo n\'a pas démarré à temps')
    exit(1)
"
